Change SemVer range for `@tenderly/hardhat-tenderly` dependency
Some time ago we had the SemVer range for the `@tenderly/hardhat-tenderly`
dependency defined as `^1.0.12` and resolved in the `yarn.lock` to `1.0.13`
version.
But we discoverd that this is problematic when `solidity-contracts` project is
used as a dependency in projects where `yarn upgrade` is run on Node.js v14,
because then the `@tenderly/hardhat-tenderly` dependency gets resolved to
`1.4.x` versions which are incompatible with Node.js v14 (to be precise, their
`tslog` subdependency isn't working on `v14`).
So we decided to limit the SemVer range for the `@tenderly/hardhat-tenderly`
dependency. We've limitted it from top to `<1.2.0` versions, which resolved the
rependency in `yarn.lock` to `1.1.6` (we didn't allow higher versions as they
proved to be problematic due to some other reasons).

But now we discovered that `1.1.6` and other `1.1.x` versions are not working
with our config either - when `npm publish --access=public --network=hardhat
--tag=development` command is run, there are errors similar to this:
```
Error:
node_modules/@nomiclabs/hardhat-ethers/internal/type-extensions.d.ts(8,10):
error TS2300: Duplicate identifier 'Libraries'.
```
or this:
```
hardhat.config.ts:87:3 - error TS2741: Property 'forkNetwork' is missing in
type '{ username: string; project: string; }' but required in type
'TenderlyConfig'.
```

So now we're specifying the range as `>=1.0.12 <1.1.0` and resolve it to the
`1.0.15` version, which does not cause any problems with publishing.