Wait for 5 confirmations before veryfing contracts
Without the change, the verification of contracts on Etherscan could sometimes
fail with error like this:
```
Verifying contract 0x... on Etherscan...
Nothing to compile
NomicLabsHardhatPluginError: Failed to send contract verification request.
Endpoint URL: https://api-goerli.etherscan.io/api
Reason: The Etherscan API responded that the address 0x... does not have
bytecode.
This can happen if the contract was recently deployed and this fact hasn't
propagated to the backend yet.
Try waiting for a minute before verifying your contract. If you are invoking
this from a script, try to wait for five confirmations of your contract
depiloyment transaction before running the verification subtask.
```