Updated hardhat, ethers, and hardhat plugin versions
The versions were updated to more recent ones, the same as used by
tbtc-v2. This update allows to elimimnate the problem when running
system tests. Although all system tests were passing, the process kept
failing with:

Error: Cannot find module './test/system/staking.test.js'

This was happening both on CI and locally. After the update, the problem
is gone.